spring:
  datasource:
    url: jdbc:mysql://uat-db:3306/onlinebank?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bank
    password: bankpw
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9811
